import * as cdk from 'aws-cdk-lib';

export interface ThumbnailMakerStackProps extends cdk.StackProps {
  /**
   * The name for the S3 bucket where original images are uploaded.
   * @default - A unique name will be auto-generated by CDK.
   */
  readonly IngressBucket?: string;

  /**
   * The name for the S3 bucket where processed thumbnails are stored.
   * @default - A unique name will be auto-generated by CDK.
   */
  readonly EgressBucket?: string;
}